
use systemx;
DROP TABLE IF EXISTS `course`;

CREATE TABLE `course` (FK_INSTRUCTOR_idxPRIMARYTITLE_UNIQUETITLE_UNIQUETITLE_UNIQUEinstructorIdtitletitle
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(128) DEFAULT NULL,
  `instructorId` int(11) DEFAULT NULL,
  
  PRIMARY KEY (`id`),
  
  UNIQUE KEY `TITLE_UNIQUE` (`title`),
  
  KEY `FK_INSTRUCTOR_idx` (`instructorId`),
  
  CONSTRAINT `FK_INSTRUCTOR_idx` 
  FOREIGN KEY (`instructorId`) 
  REFERENCES `instructor` (`id`) 
  
  ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;


SET FOREIGN_KEY_CHECKS = 1;
